FIX-PS5Controller
OnyxTronix2231/Lib-FRC pull request #41
Opened 2021-11-17 17:28 UTC by NadaVibe

2022-02-03 16:59 UTC, YuvalGur135 requested changes

2022-02-03 16:59 UTC, YuvalGur135 commented on src/joysticks/ConsoleController.java
> +        this.bumperLeft = bumperLeft;
please reorgenize the order of those params

2022-02-03 16:59 UTC, YuvalGur135 commented on src/joysticks/ConsoleController.java
> +    public int getPort(){
this func should probobly be first.

2022-02-03 16:59 UTC, YuvalGur135 commented on src/joysticks/ConsoleController.java
> +    public int getPort(){
space between -> () {

2022-02-03 16:59 UTC, YuvalGur135 commented on src/joysticks/ConsoleController.java
> +        return bumperLeft;
if u r very very very bored try to put in the same order as of the - raw butt funcs

2022-02-03 16:59 UTC, YuvalGur135 commented on src/joysticks/OnyxXboxController.java
> +        kBumperLeft(5),
blank line here

2022-02-03 16:59 UTC, YuvalGur135 commented on src/joysticks/OnyxXboxController.java
> +        kStart(8);
right order of numbers plz

2022-02-03 16:59 UTC, YuvalGur135 commented on src/joysticks/OnyxXboxController.java
> +        kLeftX(0),
blank line

2022-02-03 16:59 UTC, YuvalGur135 commented on src/joysticks/OnyxXboxController.java
> +        kRightTrigger(3);
right order of numbers plz

2022-02-03 16:59 UTC, YuvalGur135 commented on src/joysticks/PlayStation5Controller.java
> +        kSquare(1),
blank linenenenenenen

2022-02-03 16:59 UTC, YuvalGur135 commented on src/joysticks/PlayStation5Controller.java
> +        kLeftX(0),
yoohooo blank line!!! wH3rE ^Re y0U????

2022-02-08 19:37 UTC, nimrod46 approved these changes

2022-02-08 19:39 UTC, merged