added sparkmax smart motion pid, cr needed
OnyxTronix2231/Lib-FRC pull request #65
Opened 2023-01-16 18:08 UTC by benalaluf

2023-01-16 19:38 UTC, Romeore requested changes

2023-01-16 19:38 UTC, Romeore commented on src/pid/RevController.java
> +        this.sparkMax.getPIDController().setReference(setpoint / 42, controlType, slotId, feedForward);
Make a constant for this magic number

2023-01-16 19:38 UTC, Romeore commented on src/pid/RevController.java
> +        setReference(setpoint,controlType,0,0);
ctrl alt l

2023-01-16 19:38 UTC, Romeore commented on src/pid/RevSmartMotionController.java
> +        setOutPutRange(-1, 1);
What is `-1,1`

2023-01-16 20:50 UTC, nimrod46 requested changes

2023-01-16 20:50 UTC, nimrod46 commented on src/pid/RevController.java
> +        setReference(setpoint, controlType, ZERO, ZERO);
this should be `setReference(setpoint, controlType, slotId, 0);`

2023-01-16 20:57 UTC, nimrod46 commented on src/pid/RevController.java
> +    }
Remove `slotId` as a argument, use the field this object has instead

2023-01-16 20:58 UTC, nimrod46 commented on src/pid/RevSmartMotionController.java
> +                                    int maxAcceleration, int maxVelocity, int minVelocity) {
int or double?

2023-01-16 21:00 UTC, nimrod46 requested changes

2023-01-16 21:00 UTC, nimrod46 commented on src/pid/RevSmartMotionController.java
> +        setOutputRange(DEFAULT_MIN_OUTPUT, DEFAULT_MAX_OUTPUT);
Dot set it to an arbitrary value, use the value already inside `sparkMaxPIDController `

2023-01-16 21:00 UTC, nimrod46 commented on src/pid/RevConstant.java
> +    public static final int ZERO = 0;
Remove

2023-01-16 21:03 UTC, nimrod46 requested changes

2023-01-16 21:03 UTC, nimrod46 commented on src/pid/RevSmartMotionController.java
> +        this.sparkMaxPIDController.setSmartMotionAllowedClosedLoopError(tolerance, slotId);
Create `tolerance` field and update it here as well

2023-01-18 09:45 UTC, Romeore requested changes

2023-01-18 09:45 UTC, Romeore commented on src/pid/RevConstant.java
> +public class RevConstant {
`final` class, rename to `RevConstants`

2023-01-18 09:45 UTC, Romeore commented on src/pid/RevController.java
> +//by.Ben
remove

2023-01-18 09:45 UTC, Romeore commented on src/pid/RevSmartMotionController.java
> +    private int tolerance;
This is not the order according to conventions

2023-01-18 09:45 UTC, Romeore commented on src/pid/RevController.java
> +    public RevController(CANSparkMax canSparkMax,
Why do we call this parameter `canSparkMax` on 2 constructors and `sparkMax` on the other ones?

2023-01-18 09:45 UTC, Romeore commented on src/pid/RevSmartMotionController.java
> +//by.Ben
Remove..

2023-01-18 09:45 UTC, Romeore commented on src/pid/RevSmartMotionController.java
> +
Remove space

2023-01-18 09:45 UTC, Romeore commented on src/pid/RevSmartMotionController.java
> +        setMaxAndMinVelocity(maxVelocity,minVelocity);
Reformat

2023-01-18 09:45 UTC, Romeore commented on src/pid/RevSmartMotionController.java
> +                                    double maxAcceleration, double maxVelocity, double minVelocity, int tolerance) {
Get the minVelocity first and then the maxVelocity
Fix at all constructors.

2023-01-18 20:27 UTC, Romeore approved these changes

2023-01-21 13:30 UTC, nimrod46 requested changes

2023-01-21 13:30 UTC, nimrod46 commented on src/sensors/counter/RevAlternateEncoder.java
> +    }
Do not call `getAlternateEncoder` multiple times, save the encoder instance in a field

2023-01-21 13:30 UTC, nimrod46 commented on src/pid/RevSmartMotionController.java
> +        setTolerance(tolerance);
Call the private function i mentioned earlier

2023-01-21 13:30 UTC, nimrod46 commented on src/pid/RevSmartMotionController.java
> +        setTolerance(tolerance);
Move to private function which will accept all of those arguments

2023-01-21 18:29 UTC, nimrod46 approved these changes

2023-01-21 18:30 UTC, merged